#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : newt
Version  : 0.52.20
Release  : 3
URL      : http://releases.pagure.org/newt/newt-0.52.20.tar.gz
Source0  : http://releases.pagure.org/newt/newt-0.52.20.tar.gz
Summary  : A development library for text mode user interfaces
Group    : Development/Tools
License  : LGPL-2.0
Requires: newt-bin
Requires: newt-lib
Requires: newt-locales
Requires: newt-doc
BuildRequires : grep
BuildRequires : popt-dev
BuildRequires : slang-dev

%description
Newt
----
Newt is a programming library for color text mode, widget based user
interfaces.  Newt can be used to add stacked windows, entry widgets,
checkboxes, radio buttons, labels, plain text fields, scrollbars,
etc., to text mode user interfaces.  Newt is based on the slang library.

%package bin
Summary: bin components for the newt package.
Group: Binaries

%description bin
bin components for the newt package.


%package dev
Summary: dev components for the newt package.
Group: Development
Requires: newt-lib
Requires: newt-bin
Provides: newt-devel

%description dev
dev components for the newt package.


%package doc
Summary: doc components for the newt package.
Group: Documentation

%description doc
doc components for the newt package.


%package lib
Summary: lib components for the newt package.
Group: Libraries

%description lib
lib components for the newt package.


%package locales
Summary: locales components for the newt package.
Group: Default

%description locales
locales components for the newt package.


%prep
%setup -q -n newt-0.52.20

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1507068515
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
export SOURCE_DATE_EPOCH=1507068515
rm -rf %{buildroot}
%make_install
%find_lang newt

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/whiptail

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libnewt.so
/usr/lib64/pkgconfig/libnewt.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libnewt.so.0.52
/usr/lib64/libnewt.so.0.52.20

%files locales -f newt.lang
%defattr(-,root,root,-)

